apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  version: v3.9.1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels: {}
  enableAdminAPI: false
  resources: {}
