apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway-system

labels:
- pairs:
    environment: turing-talos

resources:
- ../../../envoy-gateway/base
- wildcard-certificate.yaml
- apex-certificate.yaml

patches:
- path: private-gateway.yaml
- path: public-gateway.yaml
