apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- apps-app.yaml
- argocd-app.yaml
- cert-manager-app.yaml
- cloudnative-pg-app.yaml
- envoy-gateway-app.yaml
- envoy-gateways-app.yaml
- external-secrets-app.yaml
- hetzner-acme-app.yaml
- ingress-nginx-app.yaml
- jellyfin-app.yaml
- keycloak-app.yaml
- keycloak-operator-app.yaml
- metallb-app.yaml
- opencloud-app.yaml
- pi-hole-app.yaml
- wireguard-app.yaml
